[project]
name = "advent-of-code-2024"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "pytest>=9.0.1",
]

[tool.pytest]
markers = ["slow: skip slow tests"]
